In [66]:
#Advent of Code Problem 5
#while we had a hiccup on problem 4.2 we are sadly moving on
#today seems like another challenge, which should have been expected lol

#TODO make a function to parse coords from->to into +1 lines in np, range?

import requests
import numpy as np


def getPuzzleInputAsList(day):
    cookie_file = open("../keys/session.cookie")
    cookie_raw = cookie_file.readline()
    cookie = cookie_raw.strip("\n")
    sesh = requests.Session()
    url = "https://adventofcode.com/2021/day/"+str(day)+"/input"
    req = sesh.get(url,cookies={"session":cookie})
    input_raw = req.text
    input_list = input_raw.split("\n")
    return input_list

def getLines(input_list):
    lines = np.loadtxt((x.replace('->',',')for x in input_list),delimiter=',',dtype=np.int64)
    
    return np.reshape(lines,(-1,2,2))
    
    
input_list = getPuzzleInputAsList(5)

line_coords = getLines(input_list)

#print(np.max(line_coords,axis=0))

#init a 989x991 0 array, weird size but okay??
zero_map = np.zeros((np.max(line_coords,axis=0)[1][0]+1,np.max(line_coords,axis=0)[1][1]+1))

print(line_coords)

#both of these are just giving us if they are contained in the other list not element, which 95% are because its so large
coord, coords_x, coords_y = np.intersect1d(line_coords[:,0],line_coords[:,1],return_indices=True)
coord_isin = np.isin(line_coords[:,0],line_coords[:,1])

print(coord_isin)



[[[541 808]
  [108 808]]

 [[982  23]
  [ 45 960]]

 [[558  21]
  [558 318]]

 ...

 [[607 899]
  [607 786]]

 [[139 408]
  [466 735]]

 [[ 89 274]
  [545 730]]]
[[ True  True]
 [ True  True]
 [ True False]
 [ True  True]
 [ True False]
 [False  True]
 [False  True]
 [ True False]
 [ True False]
 [False  True]
 [ True  True]
 [ True  True]
 [False  True]
 [False  True]
 [False  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True False]
 [False False]
 [ True  True]
 [False  True]
 [False  True]
 [False  True]
 [False  True]
 [False False]
 [ True  True]
 [ True False]
 [ True  True]
 [ True False]
 [False  True]
 [ True  True]
 [ True  True]
 [False  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True False]
 [ True  True]
 [ True False]
 [ True  True]
 [ True False]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True False]
 [ True  True