In [ ]:
#Advent of Code Problem 7

import requests
import numpy as np

def getPuzzleInputAsList(day): #define our function
    cookie_file = open("../keys/session.cookie") #open the keys file, this keeps us from having it in static code
    cookie_raw = cookie_file.readline() #read the keys file, leads to more secure sharing and fs controls
    cookie = cookie_raw.strip("\n") #strip the newline char
    sesh = requests.Session() #initialize our session
    url = "https://adventofcode.com/2021/day/"+str(day)+"/input" #append our day object to our destination url
    req = sesh.get(url,cookies={"session":cookie}) #make our request
    input_raw = req.text #get our request text
    input_list = input_raw.split("\n") #split our request text based on newline char
    return input_list

input_list = getPuzzleInputAsList(7)

crab_subs = np.loadtxt(input_list,delimiter=',')

crab_subs-=np.median(crab_subs) #cost for each sub, leads to negatives (cant burn negative fuel)
fuel_cost = np.sum(np.absolute(crab_subs)) #sum fuel costs after taking absolute value
print(fuel_cost)

In [21]:
#Advent of Code Problem 7 part 2 

#not sure how to approach this, initial thought was mean vs median
#this appears to give us the proper coord however our energy/fuel cost is still off

import requests
import numpy as np

def getPuzzleInputAsList(day): #define our function
    cookie_file = open("../keys/session.cookie") #open the keys file, this keeps us from having it in static code
    cookie_raw = cookie_file.readline() #read the keys file, leads to more secure sharing and fs controls
    cookie = cookie_raw.strip("\n") #strip the newline char
    sesh = requests.Session() #initialize our session
    url = "https://adventofcode.com/2021/day/"+str(day)+"/input" #append our day object to our destination url
    req = sesh.get(url,cookies={"session":cookie}) #make our request
    input_raw = req.text #get our request text
    input_list = input_raw.split("\n") #split our request text based on newline char
    return input_list

#input_list = getPuzzleInputAsList(7)
input_list = [16,1,2,0,4,2,7,1,2,14]
multi_list = [5,4,3,2,1,2,3,4,5,6]

#crab_subs = np.loadtxt(input_list,delimiter=',')
crab_subs = np.array(input_list,dtype=np.float64)

#first that comes to mind is using a np.array generated using the mean as the cental point
#+1 for each space out as the same shape as crab_subs, multiply then sum these two arrays
#ex mean is 5 shape 10, need an array = [5,4,3,2,1,2,3,4,5,6], well this aint working for some reason..
#this appears to be because of a subtraction issue, again not entirely sure a solution..
mean_dist = np.round(np.mean(crab_subs))
print(crab_subs)
crab_subs-=mean_dist #cost for each sub
print(crab_subs)
fuel_cost_proto = np.absolute(crab_subs)
print(fuel_cost_proto)
fuel_cost = fuel_cost_proto*multi_list
print(fuel_cost)
print(np.sum(fuel_cost))

[16.  1.  2.  0.  4.  2.  7.  1.  2. 14.]
[11. -4. -3. -5. -1. -3.  2. -4. -3.  9.]
[11.  4.  3.  5.  1.  3.  2.  4.  3.  9.]
[55. 16.  9. 10.  1.  6.  6. 16. 15. 54.]
188.0
